version: "3.5"

services:
  db:
    container_name: "recycling_db"
    image: mongo:5.0
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/var/lib/mongo/data

  client:
    container_name: "client"
    restart: unless-stopped
    build: ./client
    command: "npm start"
    ports:
      - "3030:3030"
    env_file:
      - ./client/.env.dev

  backend:
    container_name: "admin"
    restart: unless-stopped
    build: ./backend
    command: "npm start"
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.dev

volumes:
  mongo_data:
